sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: q4AmtDl2bNqE4TW6b67ncayJXaNy6KIKQsGv5OqJsjfPfhl49dyUUaIvTQMB3RPaGZ9ooFHNkRg1tuvV+m+MVQ8Kzdi//qa1Zfr2hLD+5wIupdQHdp36iKvTo+E+DxS23TDBEM22hj/ligR7yiO9p7VEOxduTy2ekUVtqqaLAhsly+Zvc28yRDETpL+eAfUJ4Bw76r+P6qo8tw1ns2yN/63ZO2lTUr/frsehlKEpzFSqaUj6DiWDAKdr/jK/APF2uwA8LZ4LNeTVupLWkStLaZA9dUUKbWCHez3gdchFZFbS4NXgEvxF4/YX/f1wD4EG2kAmoBhVHcQznytxuQRxEKmyrrbEJ3H7pH+yvZPu4X8Op3z+ize7xeVMEgWRa6IpDPd+uq93AURbZczOzCIMXyNOqnepL4h7c0szKMj6E3CkXoSj+6s4TYp0fIEUcxEGBZzLPtY96hKfTuJ9P1mIDkxVJnoN0DAgm8HYpt3HdJDphhwUEdHCq0EpR3yhpO3Nkmg1WZH21YimgLcm1RTkqpZ8pJGsxLoF/YNTcTYA3WkAPONlsUT4GwW+caVBzwNkTq4F45356ebX1cT2pC9XpuBF2eEMTm9mtVXL06RE5MZIkZFJeNsmD3SEKkVLe1tuPooBrvRymXiRRrTFw/EDo5BtKTAq3QiUKX2XOhMVhBc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Memoirs-of-Louis-XIV-and-His-Court-and-of-the-Regency---Volume-05_3864
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy